### ISSUE TITLE
Cannot handle paths with whitespace characters

### ISSUE THREAD

**Issue by timfish** [felixge/node-stack-trace#27]
I'm currently debugging an issue where stacks are not getting correctly parsed in Electron apps which have spaces in the name or path. This is reproduced easily in a plain nodejs v7/8 too. 

Here is the code in `whitespace tests.js`:
```
const err = new Error('some error message');
stackTrace.parse(err)
```
Here is the full stack on macOS:
```
Error: some error message
    at Context.<anonymous> (/Users/timfish/Documents/Repositories/raven-node/test/whitespace tests.js:15:15)
    at callFnAsync (/Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runnable.js:316:7)
    at Runner.runTest (/Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runner.js:444:10)
    at /Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runner.js:550:12
    at next (/Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runner.js:361:14)
    at /Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/timfish/Documents/Repositories/raven-node/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
And here is the top frame I get out of parse:
```
{ 
  filename: 'tests.js',
  lineno: 15,
  colno: 15,
  function: 'Context.<anonymous> (/Users/timfish/Documents/Repositories/raven-node/test/whitespace',
  in_app: false,
  module: 'tests' 
}
```

**Comment by timfish** [comment]
If I pass parse the above stack as a plain string `const err = {stack: 'stack copied from above'}` it works correctly, so I'm guessing there is something funky going on at runtime that I don't understand!
