### ISSUE TITLE
parsed stack trace is missing the source location of thrown Error

### ISSUE THREAD

**Issue by fogine** [felixge/node-stack-trace#29]
The following pseudo code:
```javascript

try {
    fnWhichThrows();
} catch(e) {
    console.log(e.stack);
    console.log(stackTrace.parse(e));
}
```

console.log(e.stack) prints:

```javascript
/path/to/source/file.js:22
(*$&@#(*!route.validate();
 ^
        
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    ...

```

console.log(stackTrace.parse(e)); prints:

```javascript
[ { column: 10,     
    file: 'vm.js',                                                                       
    function: 'createScript',
    line: 80,         
    method: null,            
    native: false },                                                                     
  { column: 10,               
    file: 'vm.js',  
    function: 'Object.runInThisContext',
    line: 139,                                                                           
    method: 'runInThisContext',
    native: false },
    ....
]
```

Meaning, the parsed call stack doesn't include:
> /path/to/source/file.js:22
(*$&@#(*!route.validate();
 ^

which is the most important part of the stack.   
I see [HERE](https://github.com/felixge/node-stack-trace/blob/master/lib/stack-trace.js#L26) that `node-stack-trace` always skips the first line of the call stack, why is that so?

**Comment by niemyjski** [comment]
Hi @fogine 👋

Thanks for the detailed report. You're correct — `parse()` intentionally skips the first line of `err.stack` (via `.slice(1)`) because the first line is typically the error message (e.g. `Error: something went wrong`), not a call site.

However, for `SyntaxError` and similar errors, V8 includes the source location and code snippet *before* the `at ...` frames, which means useful context gets dropped. This is a real limitation of the current parser.

A PR to optionally capture or handle these pre-frame lines would be welcome! The tricky part is distinguishing between the error message line and the source location lines that some error types include.
