### ISSUE TITLE
test-parse.js failing

### ISSUE THREAD

**Issue by tim-smart** [felixge/node-stack-trace#4]
The trace:

```
[0:00:00 0/3/3 100.0% test-parse.js]

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: getFunctionName: null != "" (#1)
    at compare (/home/tim/Projects/node-stack-trace/test/integration/test-parse.js:64:14)
    at /home/tim/Projects/node-stack-trace/test/integration/test-parse.js:68:5
    at Array.forEach (native)
    at testCompareRealWithParsedStackTrace (/home/tim/Projects/node-stack-trace/test/integration/test-parse.js:47:13)
    at Object.<anonymous> (/home/tim/Projects/node-stack-trace/test/integration/test-parse.js:82:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
node /home/tim/Projects/node-stack-trace/test/integration/test-parse.js
```

Pull requests enthusiastically encouraged :) If I get an opportunity to wrap my
head around this I'll take a crack at it.

**Comment by niemyjski** [comment]
Hi @tim-smart 👋

Thanks for reporting this back in 2013! The related fixes were merged in PR #5 and PR #11, and the parse tests are now passing on current Node versions.

Closing this as resolved. If you're still seeing issues, please feel free to reopen!
