### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/stack-trace/index.js from index.js not supported.

### ISSUE THREAD

**Issue by xorweak** [felixge/node-stack-trace#54]
### Error

```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/stack-trace/index.js from index.js not supported.
Instead change the require of index.js in index.js to a dynamic import() which is available in all CommonJS modules.

```

### Code to reproduce:

index.js
```js

import { parse } from 'stack-trace';
const err = new Error('something went wrong');
const trace = parse(err);
console.log(trace)
```

### Environment

**NodeJS 16**

package.json
```json
{
    "@babel/cli": "^7.11.6",
    "@babel/core": "^7.11.6",
    "@babel/node": "^7.10.5",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-proposal-optional-chaining": "^7.11.0",
    "@babel/plugin-proposal-private-methods": "^7.10.4",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.11.5"
}
```

.babelrc
```json
{
  "plugins": [
    "@babel/plugin-proposal-private-methods",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-class-properties"
  ],
  "ignore": [],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "16"
        }
      }
    ]
  ]
}
```

### Hypothesis

Babel is transpiling the index.js file changing the `import()` statements to `require()` which conflicts with this module, causing the **ERR_REQUIRE_ESM** error

**Comment by joshden** [comment]
I faced the same issue with my TypeScript setup using ts-node. I was previously using stack-trace 0.0.10 that was working fine. But I started seeing this error when I tried to upgrade to stack-trace 1.0.0-pre2. So for now I'm planning to stay on 0.0.10.

**Comment by mihirgarg01** [comment]
Getting the same error here. Is there a way to fix this?

**Comment by AlanGreyjoy** [comment]
My previous comment stands. If I could put everyone into one room that thinks esm belongs in the backed..... I would set fire to the room.

**Comment by yacineblr** [comment]
any news about this ?

**Comment by hkrhasan** [comment]
facing the same error is there any fix for this

`> ts-node src/index.ts

/Users/hkrhasan/development/auth-module/node_modules/.pnpm/ts-node@10.9.2_@types+node@22.1.0_typescript@5.5.4/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/hkrhasan/development/auth-module/node_modules/.pnpm/stack-trace@1.0.0-pre2/node_modules/stack-trace/index.js from /Users/hkrhasan/development/auth-module/src/utility/logger.ts not supported.
Instead change the require of index.js in /Users/hkrhasan/development/auth-module/src/utility/logger.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/hkrhasan/development/auth-module/node_modules/.pnpm/ts-node@10.9.2_@types+node@22.1.0_typescript@5.5.4/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/hkrhasan/development/auth-module/src/utility/logger.ts:4:23)
    at m._compile (/Users/hkrhasan/development/auth-module/node_modules/.pnpm/ts-node@10.9.2_@types+node@22.1.0_typescript@5.5.4/node_modules/ts-node/dist/index.js:857:29) {
  code: 'ERR_REQUIRE_ESM'
}
`

**Comment by niemyjski** [comment]
Hi @xorweak and everyone affected 👋

Thanks for the detailed report. This is a known pain point — the `1.0.0-pre2` version is ESM-only, which breaks consumers that use `require()` (including Babel and ts-node setups that transpile `import` to `require()`).

**Workaround for now:** Stay on `stack-trace@0.0.10` if your project uses CommonJS or a transpiler that emits `require()`.

We're aware this needs a proper solution — likely either shipping a dual CJS/ESM package or ensuring the `latest` npm dist-tag doesn't point to the pre-release. Leaving this open as it affects multiple users.

**Comment by niemyjski** [comment]
Really feels like we should just drop babel and target straight esm, that is the future. @felixge any preferences on this.

**Comment by felixge** [comment]
@niemyjski I got no horse in this race anymore, so feel free to do whatever makes sense to you 🙇
